name: SetHome
version: '${project.version}'
author: Beeted_
main: beeted.sethome.SetHome
api-version: 1.13

commands:
  home:
    description: Open the home menu.
    usage: /home
  reload:
    description: Reloads the plugin config.
    usage: /home reload