name: SetHome
version: '${project.version}'
author: Beeted_
main: beeted.sethome.SetHome
api-version: 1.13

commands:
  homegui:
    description: Functions main command.
    aliases: [homegui]
  home:
    description: Main homes command.
    aliases: [homes]
